# These are supported funding model platforms

github: djdarcy # GitHub Sponsors
ko_fi: djdarcy # Ko-fi donations
buy_me_a_coffee: djdarcy # Buy Me a Coffee

# Other platforms (uncomment if you have accounts)
#patreon: # Patreon username
#open_collective: # Open Collective username
#tidelift: # Platform-name/package-name (e.g., npm/babel)
#community_bridge: # Community Bridge project-name
#liberapay: # Liberapay username
#issuehunt: # IssueHunt username
#otechie: # Otechie username
#lfx_crowdfunding: # LFX Crowdfunding project-name
#custom: ['https://example.com/sponsor'] # Up to 4 custom URLs